version: '3.6'
services:
    web:
        build: .
        container_name: myphpapacheserver
        volumes:
        - .:/var/www/html/
        ports:
        - "80:80"
        networks:
            - web_api_network
#--------------------------
    mysql:
        image: "mysql:latest"
        container_name: mysql
        command: ['--default-authentication-plugin=mysql_native_password']
        environment:
            - MYSQL_DATABASE=default_db
            - MYSQL_ROOT_PASSWORD=my-pass
            - MYSQL_USER=user-name
            - MYSQL_PASSWORD=my-user-pass
        volumes:
            - mysqldata:/var/lib/mysql
        ports:
            - 3306:3306
        restart: always
        networks:
            - web_api_network
#--------------------------
    phpmyadmin:
        image: "phpmyadmin/phpmyadmin"
        container_name: phpmyadmin
        environment:
            - PMA_ARBITRARY=1
        ports:
            - 8080:80
        networks:
            - web_api_network

volumes:
    mysqldata:

networks: 
    # set all containers in external network
    web_api_network:
        external: true